<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Jedi</string>
	<key>fileTypes</key>
	<array>
		<string>jedi</string>
	</array>
	<key>scopeName</key>
	<string>source.jedi</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Unbuffered (jedi-only) comments.</string>
			<key>name</key>
			<string>comment.unbuffered.block.jedi</string>
			<key>begin</key>
			<string>^(\s*)--</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Embedded PHP Code.</string>
			<key>name</key>
			<string>source.php.embedded</string>
			<key>begin</key>
			<string>^(\s*)(-)\s*</string>
			<key>end</key>
			<string>^(?!\n|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Unbuffered (jedi-only) inline comments.</string>
			<key>name</key>
			<string>comment.unbuffered.inline.jedi</string>
			<key>begin</key>
			<string>^(\s*)//</string>
			<key>end</key>
			<string>^(?!\n|\s*$)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Buffered (html) comments.</string>
			<key>name</key>
			<string>string.comment.buffered.block.jedi</string>
			<key>begin</key>
			<string>^(\s*)!</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Script tag with JavaScript code.</string>
			<key>name</key>
			<string>source.js.embedded</string>
			<key>begin</key>
			<string>^(\s*)(script)((\.[\w\-_]+\b)*(#[\w\-_]+)?)(\s*(if)\b)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.script.jedi</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.js</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>keyword.control.jedi</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag_attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag_mixin</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#script_definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#script_statement</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Style tag with CSS code.</string>
			<key>name</key>
			<string>source.css.embedded</string>
			<key>begin</key>
			<string>^(\s*)(style)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.style.jedi</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#style_statement</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Mixin block</string>
			<key>name</key>
			<string>source.block.mixin.jedi</string>
			<key>begin</key>
			<string>^(\s*)::([A-Za-z]+\d*)((\.[\w\-_]+\b)*(#[\w\-_]+)?)\s*\(([\s\w\-\$_,]*)\)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.jedi</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.js</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.mixin.jedi</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag_attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Import Keyword.</string>
			<key>name</key>
			<string>source.block.import.jedi</string>
			<key>begin</key>
			<string>^(\s*):\s*(import)\b(.*)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.jedi</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.import.jedi</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.block.layout.jedi</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>External Keyword.</string>
			<key>name</key>
			<string>source.block.external.jedi</string>
			<key>begin</key>
			<string>^(\s*):\s*(external)\b([^,]*)(,([^,]*))*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.external.jedi</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.jedi</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.jedi</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.block.layout.jedi</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Flow Keywords.</string>
			<key>name</key>
			<string>source.block.flow.jedi</string>
			<key>begin</key>
			<string>^(\s*)(?=:\s*)</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#for_in_statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#general_statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.block.jedi</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Layout block</string>
			<key>name</key>
			<string>source.block.layout.jedi</string>
			<key>begin</key>
			<string>^(\s*)(#[\w\-_]+)(::after)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.jedi</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.class.afterblock.jedi</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.block.jedi</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Common tag block.</string>
			<key>name</key>
			<string>source.block.jedi</string>
			<key>begin</key>
			<string>^(\s*)([A-Za-z]+\d*)(\s*&gt;\s*[A-Za-z]+\d*)?((\.[\w\-_]+\b)*(#[\w\-_]+)?)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.jedi</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.jedi</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.language.js</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag_attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag_mixin</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>script_definition</key>
		<dict>
			<key>begin</key>
			<string>^(\s*)"</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>script_statement</key>
		<dict>
			<key>begin</key>
			<string>^(\s*)!</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.js</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/|^(?!(\1\s)|\s*$)</string>
					<key>name</key>
					<string>comment.block.js</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>style_statement</key>
		<dict>
			<key>begin</key>
			<string>^(\s*)!</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.css</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/|^(?!(\1\s)|\s*$)</string>
					<key>name</key>
					<string>comment.block.css</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<key>tag_attribute</key>
		<dict>
			<key>begin</key>
			<string>(\s*)(?=@)</string>
			<key>end</key>
			<string>$</string>
			<key>match</key>
			<string>\s+(@[\w\-_]+)(\s*\=\s*)?(('[^']*')|("[^"]*"))?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.jedi</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.jedi</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.quoted.attribute.jedi</string>
				</dict>
			</dict>
		</dict>
		<key>tag_mixin</key>
		<dict>
			<key>begin</key>
			<string>(\s*)(?=\=)</string>
			<key>end</key>
			<string>$</string>
			<key>match</key>
			<string>(=)\s*\[([\s\w,]*)\]</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.jedi</string>
				</dict>
				<!--<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.mixin.jedi</string>
				</dict>-->
			</dict>
		</dict>
		<key>for_in_statement</key>
		<dict>
			<key>begin</key>
			<string>:(\s*)(for)\s*((\([\s\w,]*\))|\w*)\s*(in)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.jedi</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.jedi</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
		</dict>
		<key>general_statement</key>
		<dict>
			<key>begin</key>
			<string>:(\s*)(let|if|else if|else|unsafe)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.jedi</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>uuid</key>
	<string>ef3ba757-0e78-44e9-b108-afa601818880</string>
</dict>
</plist>
